### ISSUE TITLE
How to create and use a virtual device

### ISSUE THREAD

**Issue by albfan** [Vantskruv/wejoy#10]
After install and run with the example.lua modified:

```
v_devices = 
{
	v0 = 
	{
		buttons = 3,
		axes = 2
	}
}

send_button_event(0, 0, 1)
send_axis_event(0, 0, 180)
send_button_event(0, 0, 0)

get_vjoy_button_status(0, 0)
get_vjoy_axis_status(0, 0)
```

Seems it creates the virtual device but then it do not launch any axis change or button change:

```
$ sudo wejoy wejoy.lua 
Opening virtual keyboard device.
Creating virtual keyboard device.
Successfully created virtual keyboard device.
Error: failed to load (wejoy.lua)
wejoy.lua:14: attempt to call global 'get_vjoy_button_status' (a nil value)
Success
```

Apart from that, how do we parse the keyboard to, for example, use two keys to move an axis from -32767 to 32767?

My idea is to create 4 axis: (long press to move position incrementally)
- <kbd>Q</kbd>-<kbd>A</kbd>
- <kbd>W</kbd>-<kbd>S</kbd>
- <kbd>E</kbd>-<kbd>D</kbd>
- <kbd>R</kbd>-<kbd>F</kbd>
 
and 4 toggle buttons with:
- <kbd>U</kbd>
- <kbd>I</kbd>
- <kbd>O</kbd>
- <kbd>P</kbd>

Do you think it is possible?

**Comment by albfan** [comment]
I see, `CVirtualKeyboard::CVirtualKeyboard` is available for output, but not for input.

I think something like:

```
devices = {
   k = {
     b0 = U,
     a0 = Q-A
   }
}

v_devices = 
{
	v0 = 
	{
		buttons = 3,
		axes = 2
	}
}

function k_b0_event(value)
	if value == 1 then
		send_button_event(0, 0, 1)
	else
		send_button_event(0, 0, 0)
	end
end

```

can work to read keyboard, create those buttons and axes and then execute on virtual joystick

What do you think?

**Comment by Vantskruv** [comment]
Oh my, I have not been active at all, and forgot to answer your question.
It is of course possible to implement such a function, keyboard detection. When I developed Wejoy, I first did not see any need of it, but currently someone needs it. ;)

Though, I currently do not have energy to implement it right now, as this project was just something I felt to do for short amount of time a couple of years ago, and now I do not have any use for it myself...

Maybe someone else have time to implement such function, but I keep this open, maybe it is easier than I think it is (I forgot all the code, need to read through and test which takes time).

**Comment by Vantskruv** [comment]
@albfan Magically, I got some energy to implement of what you requested. I will update the source soon! :)

**Comment by albfan** [comment]
Great, you can push a WIP if you want and I would help to finish it.

Just let me know.

**Comment by Vantskruv** [comment]
I did a prematured (stupid me) release for version 0.2. How does it work?

**Comment by albfan** [comment]
All you did makes sense but I think it needs some polish:

```
$ sudo wejoy example.lua 
WeJoy v0.2 by Johannes Bergmark
Error: failed to load (example.lua)
example.lua:17: '}' expected (to close '{' at line 3) near 'kbd1'
Success
```

After adding some commas to example.lua

```
$ sudo wejoy example.lua 
WeJoy v0.2 by Johannes Bergmark
Error: can't get [devices.d2.vendorid]. 1:At level 1, d2 is not defined
WARNING: Joystick 44f:402 is not found.
```

I created this for test:

```
$ cat config.lua 
devices = 
{
	kbd0 = "/dev/input/event6"
}

v_devices = 
{
	v0 = 
	{
		buttons = 3,
		axes = 2
	}
}

function kbd0_pressed(value)
	if value == KEY_W then
		send_button_event(0, 1, 1)
	end
end

function kbd0_released(value)
	if value == KEY_W then
		send_button_event(0, 1, 0)
	end
end
```

I get the device from evtest:

```
$ sudo evtest 
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Power Button
/dev/input/event1:	Lid Switch
/dev/input/event2:	Sleep Button
/dev/input/event3:	Power Button
/dev/input/event4:	Video Bus
/dev/input/event5:	Video Bus
/dev/input/event6:	AT Translated Set 2 keyboard
...
```

But seems wejoy assume there're two keyboards, etc...

```
$ sudo wejoy config.lua 
WeJoy v0.2 by Johannes Bergmark
Error: can't get [devices.d0.vendorid]. 1:At level 1, d0 is not defined
Error: can't get [devices.kbd1]. 2:At level 1, kbd1 is not defined
Error: can't get [v_devices.v1.buttons]. 1:At level 1, v1 is not defined
ERROR -1: Failed opening virtual device 0.
```

The thing is, how do I make wejoy to stay if I only setup a keyboard?, wejoy seems to end. Is there any wait I can setup so I end the virtual device with Ctrl+C.

I'm testing the joystick with `jstest`

**Comment by Vantskruv** [comment]
Have you tried running:
sudo modprobe uinput
before starting wejoy?

**Comment by Vantskruv** [comment]
I noticed I mistakenly did not push the Luascript.h file for the project (not removing the false errors).
I have pushed that file, and also added some commas to correct the format errors in the example.lua.
Thanks for that.

Otherwise, it works okay for me...

**Comment by albfan** [comment]
Everything is working find now, This deserves a 1.0 release!

![wejoy showing keyboard to virtual emulation](https://user-images.githubusercontent.com/220968/62948552-d8dbfe00-bde4-11e9-8858-022cb7d815f3.gif)

**Comment by Vantskruv** [comment]
Nice! I am happy it works for you!
There wil be no 1.0 release, it will be a 0.21 release.
The quality requirements is too much if it would be a 1.0 release. :D

**Comment by albfan** [comment]
Sure. I want to simulate a drone controller, so I want that <kbd>A<kbd>-<kbd>S<kbd> simulating an axis (recovering to center optionally without pressing keys)

I guess that's pure Lua, isn't it?

**Comment by Vantskruv** [comment]
I hope so yes. :)
Though, I have not scripted any advanced things in Lua. It was mainly created for myself, emulating three-position switches to trigger button presses when they go the middle-state. 
It is fun to see it is used for other things aswell. :+1: 

An interesting project you have! :)
But I cannot guarantee that your drone will not crash because of WeJoy, I really hope not! ;)
