### ISSUE TITLE
Lua builtin functions not available

### ISSUE THREAD

**Issue by ahigerd** [Vantskruv/wejoy#14]
In order to simplify binding a series of buttons, I wrote a Lua function that iterates over a mapping table. Unfortunately, I got an error saying that `pairs` was a nil value.

This can be fixed by rearranging `LuaScript::LuaScript` to call `luaL_openlibs` before calling `luaL_loadfile` instead of the other way around.

**Comment by Vantskruv** [comment]
Added.
https://github.com/Vantskruv/wejoy/commit/0dc9f29ac8c983f7a9adaf2b641e0d38ad795be8
