### ISSUE TITLE
Build errors on Ubuntu 14.04

### ISSUE THREAD

**Issue by dorinclisu** [Vantskruv/wejoy#2]
I installed the liblua and x11 dependencies however I get this:

<pre>
dorin@dorin-PX:~/Downloads/wejoy$ sh make.sh

/tmp/ccPpFIUk.o: In function `suinput_get_uinput_path()':
suinput.c:(.text+0x1fa): undefined reference to `udev_new'
/tmp/cce5QcZx.o: In function `Joystick::retrieveID(int, int&, int&)':
joystick.cc:(.text+0xeae): undefined reference to `udev_new'
LuaScript.cc:(.text+0x11): undefined reference to `luaL_newstate'
/tmp/cca1ILwB.o: In function `l_send_keyboard_event(lua_State*)':
main.cc:(.text+0x46c): undefined reference to `lua_tonumberx'
collect2: error: ld returned 1 exit status
</pre>

**Comment by Vantskruv** [comment]
It seems you are missing the development files for liblua and libudev.

Depending on what version of Linux you have, there may be different versions of liblua. Currently for me it is 5.3, but it may be for you 5.2.

You may search for what libraries are available for you in your current distro:
$ apt-cache search liblua

Installing the liblua (note in your case it may be liblua5.2-dev) and libudev development files:
$ sudo apt-get install liblua5.3-dev
$ sudo apt-get install libudev-dev

**Comment by dorinclisu** [comment]
I found the problem, please change your makefile to:
<pre>
g++ -Wall -std=c++11 suinput.c joystick.cc LuaScript.cc CVirtualJoy.cc CVirtualKeyboard.cc -o wejoy main.cc -ludev -lpthread -lX11 -llua5.2
</pre>
<url>https://stackoverflow.com/questions/34403703/how-to-fix-linker-errors-for-libudev-on-ubuntu-15/34403797#34403797?newreg=8a244f936fc44b0e83ed440c4b1be934</url>

**Comment by Vantskruv** [comment]
Thank you very much for your report. I'll change the makefile.
