### ISSUE TITLE
X-Plane not detecting button presses

### ISSUE THREAD

**Issue by johnswanson** [Vantskruv/wejoy#3]
Hey, thanks so much for creating this! Just wondering if you ever got this working for X-Plane with the Warthog (I found this repo from the forum, have the exact same setup).

I can see the virtual devices, I can watch the events streaming in with `evtest`, I modified the permissions to `0666` on the input devices... but X-Plane is still just detecting the "non-virtual" buttons.

Any advice?

Thanks!

**Comment by johnswanson** [comment]
(Also, sorry for creating an issue when your code seems to be working perfectly!) :)

**Comment by johnswanson** [comment]
Turns out X-Plane checks to see whether a given input is a "joystick" in part by checking that it has axes, not just buttons. Adding a meaningless axis to the virtual device causes X-Plane to pick it up.

I modified `warthog_throttle.lua` to contain the following definition for `v_devices`, will make a PR if you want (1 axis might be necessary, just haven't checked yet):

```
v_devices =
{
  v0 =
  {
    buttons = 13,
    axes = 2
  }
}
```

**Comment by Vantskruv** [comment]
Thanks for pointing it out, and I'm glad someone is using it. Though it feels it needs some more love, but I have not felt to make time with it, as I've been mainly using X-Plane for Windows. If you are flying the TU154 in X-Plane, check out my other project.

Happy flying!
