### ISSUE TITLE
Thrustmaster Warthog Throttle not detected

### ISSUE THREAD

**Issue by xpd259** [Vantskruv/wejoy#6]
Hello, 

I'm trying to setup my new warthog with wejoy and I've managed to get
the Joystick part to work but the throttle is proving to be troublesome 

```
┌─[dthomas@thadeus] - [~/code/wejoy] - [Fri Dec 09, 03:15]
└─[$] <git:(master*)> lsusb               
...
Bus 002 Device 005: ID 044f:0402 ThrustMaster, Inc. 
...
Bus 003 Device 013: ID 044f:0404 ThrustMaster, Inc. 
...
┌─[dthomas@thadeus] - [~/code/wejoy] - [Fri Dec 09, 03:16]
└─[$] <git:(master*)> sudo ./wejoy warthog_throttle.lua
Opening virtual keyboard device.
Creating virtual keyboard device.
Successfully created virtual keyboard device.
Error: can't get [devices.d1.vendorid]. 1:At level 1, d1 is not defined
WARNING: Joystick 44f:404 is not found.
```

wejoy isn't detecting the throttle.

not sure what other debugging info I can give or how to get it.

**Comment by xpd259** [comment]
sorry forgot to say
I'm running Debian AMD64 (testing)

**Comment by Vantskruv** [comment]
Hmm, that is strange. It should be found. Can you show me your LUA file, maybe there is some extra space or character somewhere?

**Comment by xpd259** [comment]
I was just using the example ones from the repo, I'd not even got as far as writing my own 😟

**Comment by Vantskruv** [comment]
Eeeek! It works without any problems for me. I'm not sure how to debug this, and I am not an expert too. :( 
I'm using Debian Testing 64 bit too with kernel 4.8.0-1.

Do the warthog throttle work well otherwise?

**Comment by xpd259** [comment]
I only got it today, but AFAIK it's all good!
I've been using it with X-Plane11 and it was detected out of the box.
and while I've not played with all of the buttons it seems to work fine

**Comment by Vantskruv** [comment]
That is good it works out of the box. :) I tried just recompile a fresh build from current git, and there was no problem loading the warthog_throttle.lua.

Can you show me directory folder of '/dev/input/'?

There should be files called something like 'js0', 'js1', 'js2' and so on there. These files represents the joystick devices you have connected to your computer.

**Comment by xpd259** [comment]
```
└─[$] <> ls /dev/input/        
by-id    event0  event10  event12  event14  event16  event18  event2   event21  event23  event25  event4  event6  event8  js1  js3   mouse0
by-path  event1  event11  event13  event15  event17  event19  event20  event22  event24  event26  event5  event7  event9  js2  mice  mouse1
┌─[dthomas@thadeus] - [~] - [Fri Dec 09, 07:30]
```

there is a js1 , js2, js3
also the permissions are as follows
```
┌─[dthomas@thadeus] - [~] - [Fri Dec 09, 07:33]
└─[$] <> stat /dev/input/js*
  File: '/dev/input/js1'
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 6h/6d   Inode: 12229       Links: 1     Device type: d,1
Access: (0664/crw-rw-r--)  Uid: (    0/    root)   Gid: (  108/   input)
Access: 2016-12-09 18:16:50.872854112 +0000
Modify: 2016-12-09 18:16:50.872854112 +0000
Change: 2016-12-09 18:16:50.872854112 +0000
 Birth: -
  File: '/dev/input/js2'
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 6h/6d   Inode: 8443338     Links: 1     Device type: d,2
Access: (0664/crw-rw-r--)  Uid: (    0/    root)   Gid: (  108/   input)
Access: 2016-12-09 19:30:14.287498515 +0000
Modify: 2016-12-09 19:30:14.287498515 +0000
Change: 2016-12-09 19:30:14.287498515 +0000
 Birth: -
  File: '/dev/input/js3'
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 6h/6d   Inode: 8453282     Links: 1     Device type: d,3
Access: (0664/crw-rw-r--)  Uid: (    0/    root)   Gid: (  108/   input)
Access: 2016-12-09 19:30:18.947572643 +0000
Modify: 2016-12-09 19:30:18.947572643 +0000
Change: 2016-12-09 19:30:18.947572643 +0000
 Birth: -
```

it might be worth noting that the joystick element of one of the sample files works
when I deleted the throttle part from the lua file.

**Comment by Vantskruv** [comment]
I think I found the bug.
When searching for 'js' devices in '/dev/input' folder, it assumes the first device is 0. It searches until device number is not found, and then ends the search. I.e. if js0 is not found, it assumes there are no more devices to search for.

**Comment by Vantskruv** [comment]
Just to notify, I need to think about a good fix for this. Hold on!

**Comment by xpd259** [comment]
ahh. makes sense 👍 
I think I know why too. my Evil keyboard and mouse is a Microsoft ergonomic one 
and that shows up as a joystick (yeah go figure) I have a Udev rule to delete the offending js entry to stop games and stuff going crazy


 https://github.com/denilsonsa/udev-joystick-blacklist

**Comment by Vantskruv** [comment]
A good way to find bugs in other programs. :)
I've not yet update the sourcecode in repository, but I've attached the updated file in this post.
Rename it to 'joystick.cc' and recompile the program.
[joystick.txt](https://github.com/Vantskruv/wejoy/files/643168/joystick.txt)

**Comment by xpd259** [comment]
sadly the same error 

```
sudo ./wejoy warthog_throttle.lua 
Opening virtual keyboard device.
Creating virtual keyboard device.
Successfully created virtual keyboard device.
Error: can't get [devices.d1.vendorid]. 1:At level 1, d1 is not defined
Unable to find parent USB device index 4
WARNING: Joystick 44f:404 is not found.
```

**Comment by Vantskruv** [comment]
Damnit, and I fast too fast adding it to repository.

**Comment by xpd259** [comment]
oops, sorry I was AFK for a while.

**Comment by xpd259** [comment]
let me reboot with my mouse and keyboard unplugged then plug them in last
so make them /dev/input/js3 rather than js0 and see if that works

**Comment by Vantskruv** [comment]
Hopefully that will work. I'm not sure if could manage solving this problem for now. I was planning to fly the DC6 at VATSIM, but coding is fun too! :)

**Comment by xpd259** [comment]
go fly 💃
 I'm feeling really bad for finding a real problem :( 
/me shakes fist at silly Microsoft mouse

**Comment by Vantskruv** [comment]
So it was the mouse huuh? It does work now?

**Comment by xpd259** [comment]
yeah, it was the mouse/keyboard
I had to borrow my wife's keyboard to sign in but it works now

maybe I can write a udev rule to make it always js3 :/ if that's even possible

**Comment by Vantskruv** [comment]
Good, hope your wife does not notice anything. Happy flying with you and I'm glad it after all will work for you. :)

Closing topic now!
